doctrine:
  dbal:
    driver: pdo_mysql
    host: "%env(string:DATABASE_HOST)%"
    user: "%env(string:DATABASE_USER)%"
    password: "%env(string:DATABASE_PASSWORD)%"
    dbname: "%env(string:DATABASE_NAME)%"
    server_version: "%env(string:DATABASE_SERVER_VERSION)%"
    charset: utf8mb4
    default_table_options:
      collate: utf8mb4_unicode_ci
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App