nelmio_cors:
  defaults:
    origin_regex: false
    allow_credentials: false
    allow_origin: [ ]
    allow_methods: [ ]
    allow_headers: [ ]
    expose_headers: [ ]
    max_age: 0
    hosts: [ ]
  paths:
    '^/api/':
      allow_origin: [ '*' ]
      allow_headers: [ '*' ]
      allow_methods: [ 'OPTIONS', 'POST', 'GET', 'PUT', 'DELETE', 'PATCH', 'LOCK', 'UNLOCK' ]
      max_age: 3600
    '^/':
      origin_regex: true
      allow_origin: [ '*' ]
      allow_headers: [ '*' ]
      allow_methods: [ 'OPTIONS', 'POST', 'GET', 'PUT', 'DELETE', 'PATCH', 'LOCK', 'UNLOCK' ]
      max_age: 3600

