version: "3.8"

networks:
  caddy:
    external: true

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  caddy_config_front:
  caddy_data_front:
  caddy_data_back:
  caddy_config_back:

services:
  database:
    image: mariadb:10.6.12
    container_name: database
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: twitchOverlay
      MYSQL_PASSWORD: password

  node:
    build:
      context: ./front
      target: app_node
    restart: unless-stopped

  php:
    build:
      context: ./back
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-6.1}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      APP_ENV: prod
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: twitchOverlay
      DATABASE_SERVER_VERSION: mariadb-10.6.12

  caddy_back:
    build:
      context: ./back
      target: app_caddy
    ports:
      # HTTP
      - target: 80
        published: ${FRONT_HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${FRONT_HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${FRONT_HTTP3_PORT:-443}
        protocol: udp
    networks:
      - caddy
    depends_on:
      - php
    environment:
      SERVER_NAME: ${CADDY_BACK_NAME:-api.localhost, caddy:80}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data_back:/data
      - caddy_config_back:/config

  caddy_front:
    build:
      context: ./front
      target: app_caddy
    ports:
      # HTTP
      - target: 80
        published: ${FRONT_HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${FRONT_HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${FRONT_HTTP3_PORT:-443}
        protocol: udp
    depends_on:
      - node
    environment:
      SERVER_NAME: ${CADDY_FRONT_NAME:-localhost, caddy:80}
    restart: unless-stopped
    volumes:
      - caddy_data_front:/data
      - caddy_config_front:/config