name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: php-actions/composer@v6
        with:
          version: 2.5
          php_version: "8.1"
          working_dir: "back"
      - uses: php-actions/phpunit@v3
        with:
          version: "10.0.12"
          php_version: "8.1"
          vendored_phpunit_path: "back/vendor/bin/phpunit"
          configuration: "back/phpunit.xml.dist"
          memory_limit: "256M"