name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          working_dir: "back"
      - uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8mb4'
          mariadb version: '10.6.12'
          mysql user: root
          mysql password: password
          mysql root password: password
          mysql database: test
      - name: Start Ubuntu MySQL (SUDO)
        run: |
          sudo /lib/systemd/systemd-sysv-install enable mysql
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service
          sudo systemctl status mysql.service
      - name: Setup tests
        run: "cd back && php bin/console --env=test d:s:create && php bin/console d:f:load"
      - name: Tests
        uses: php-actions/phpunit@v3
        with:
          version: "10.0.12"
          php_version: "8.1"
          configuration: "back/phpunit.xml.dist"
          memory_limit: "256M"