name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          version: "10.0.12"
          php_version: "8.1"
          configuration: "back/phpunit.xml.dist"
          memory_limit: "256M"